In [ ]:
import pandas as pd
import unicodedata

In [13]:
df = pd.read_csv('datatran2007.csv', sep=';',  encoding='latin1')
df

C:\Users\kauaviado\AppData\Local\Temp\ipykernel_19528\2605497619.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('datatran2007.csv', sep=';',  encoding='latin1')

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,uso_solo,ano,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos
0,10,11/06/2007,Segunda,15:30:00,MG,381,623.2,OLIVEIRA,Falta de atenção,Colisão frontal,...,Rural,2007,9,0,4,0,5,0,4,6
1,10,11/06/2007,Segunda,15:30:00,MG,381,623.2,OLIVEIRA,Falta de atenção,Colisão frontal,...,Rural,2007,9,0,4,0,5,0,4,6
2,1032898,13/08/2007,Segunda,14:25:00,MG,40,585.5,ITABIRITO,Outras,Saída de Pista,...,Rural,2007,3,0,0,1,2,0,1,1
3,1051130,12/02/2007,Segunda,02:10:00,MA,135,11.0,SAO LUIS,Animais na Pista,Atropelamento de animal,...,Urbano,2007,5,2,2,1,0,0,3,1
4,1066824,20/11/2007,Terça,05:30:00,CE,222,30.8,CAUCAIA,Defeito mecânico em veículo,Capotamento,...,Rural,2007,1,0,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127670,956310,15/12/2007,Sábado,08:00:00,MG,50,22.0,ARAGUARI,Falta de atenção,Colisão com objeto fixo,...,Rural,2007,4,0,2,2,0,0,4,1
127671,964123,16/06/2007,Sábado,14:50:00,PR,373,268.3,PRUDENTOPOLIS,Outras,Danos Eventuais,...,Rural,2007,3,0,0,1,2,0,1,2
127672,985245,11/12/2007,Terça,14:00:00,MT,70,697.1,CACERES,Outras,Colisão frontal,...,Rural,2007,9,1,0,6,2,0,6,3
127673,987413,09/05/2007,Quarta,14:50:00,SC,470,65.8,INDAIAL,Falta de atenção,Colisão Transversal,...,Urbano,2007,3,0,3,0,0,0,3,2
127674,988556,07/02/2007,Quarta,07:15:00,BA,324,603.5,SIMOES FILHO,Falta de atenção,Colisão traseira,...,Urbano,2007,2,0,0,0,2,0,0,2

In [14]:
df2008 = pd.read_csv('datatran2008.csv', sep=';', encoding='latin1')
df2008

C:\Users\kauaviado\AppData\Local\Temp\ipykernel_19528\1930006106.py:1: DtypeWarning: Columns (5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df2008 = pd.read_csv('datatran2008.csv', sep=';', encoding='latin1')

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,uso_solo,ano,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos
0,1012870,25/11/2008,Terça,16:00:00,DF,70,5,BRASILIA,Outras,Colisão traseira,...,Urbano,2008,3,0,1,0,2,0,1,2
1,1023692,09/11/2008,Domingo,10:10:00,MA,316,284,BELA VISTA DO MARANHAO,Outras,Tombamento,...,Rural,2008,12,2,7,2,1,0,9,1
2,1027252,27/11/2008,Quinta,09:20:00,PE,101,47.6,IGARASSU,Falta de atenção,Colisão traseira,...,Urbano,2008,4,0,2,0,2,0,2,3
3,1029670,11/01/2008,Sexta,22:00:00,MA,316,432.1,PERITORO,Ultrapassagem indevida,Colisão frontal,...,Rural,2008,4,2,2,0,0,0,2,2
4,1038085,07/05/2008,Quarta,07:05:00,RO,364,719.6,PORTO VELHO,Falta de atenção,Colisão Transversal,...,Urbano,2008,3,0,2,0,1,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141038,968965,27/09/2008,Sábado,17:40:00,RJ,493,3.0,ITABORAI,Outras,Colisão frontal,...,Urbano,2008,6,0,4,0,1,1,4,3
141039,971288,28/03/2008,Sexta,19:15:00,MG,381,413.5,CAETE,Outras,Colisão traseira,...,Rural,2008,2,0,0,0,2,0,0,2
141040,974654,28/12/2008,Domingo,14:30:00,MA,135,490.0,PARAIBANO,Falta de atenção,Colisão frontal,...,Urbano,2008,2,1,0,0,1,0,0,2
141041,976115,16/08/2008,Sábado,06:00:00,RR,174,452.8,MUCAJAI,Falta de atenção,Saída de Pista,...,Rural,2008,27,7,9,11,0,0,20,1
141042,997721,09/12/2008,Terça,07:30:00,RJ,101,320.0,NITEROI,Outras,Colisão traseira,...,Urbano,2008,4,0,1,0,3,0,1,3

In [15]:
df2009 = pd.read_csv('datatran2009.csv', sep=';', encoding='latin1')
df2009

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,uso_solo,ano,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos
0,1003202,10/11/2009,Terça,14:10:00,MG,381,495.0,BETIM,Velocidade incompatível,Colisão traseira,...,Urbano,2009,5,0,4,0,1,0,4,2
1,1005196,16/10/2009,Sexta,04:35:00,MG,251,419.6,GRAO MOGOL,Outras,Colisão frontal,...,Rural,2009,9,4,0,5,0,0,5,2
2,1010521,20/09/2009,Domingo,20:00:00,PI,316,24.0,TERESINA,Dormindo,Saída de Pista,...,Rural,2009,6,0,2,4,0,0,6,1
3,1013808,17/05/2009,Domingo,15:45:00,RJ,101,429.0,MANGARATIBA,Falta de atenção,Colisão Transversal,...,Urbano,2009,2,0,0,0,2,0,0,2
4,1014343,05/07/2009,Domingo,17:30:00,PE,101,59.2,RECIFE,Outras,Queda de motocicleta / bicicleta / veículo,...,Rural,2009,1,0,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158641,992957,01/08/2009,Sábado,20:30:00,BA,242,770.0,BARREIRAS,Outras,Atropelamento de pessoa,...,Rural,2009,2,0,0,1,0,1,1,1
158642,995918,15/01/2009,Quinta,09:45:00,MT,364,292.0,JACIARA,Falta de atenção,Colisão traseira,...,Rural,2009,3,0,0,0,3,0,0,3
158643,999120,30/06/2009,Terça,22:00:00,RJ,40,73.0,PETROPOLIS,Outras,Capotamento,...,Urbano,2009,1,0,0,0,1,0,0,1
158644,999150,14/07/2009,Terça,08:15:00,GO,414,281.0,VILA PROPICIO,Outras,Colisão Transversal,...,Rural,2009,3,0,0,2,1,0,2,2
158645,999845,16/06/2009,Terça,02:00:00,RJ,101,154.0,MACAE,Ultrapassagem indevida,Colisão frontal,...,Rural,2009,3,3,0,0,0,0,0,2

concatenando 3 csv de 2007 há 2009

In [16]:
frames = [df, df2008, df2009]

df_concat = pd.concat(frames)

df_concat

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,uso_solo,ano,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos
0,10,11/06/2007,Segunda,15:30:00,MG,381,623.2,OLIVEIRA,Falta de atenção,Colisão frontal,...,Rural,2007,9,0,4,0,5,0,4,6
1,10,11/06/2007,Segunda,15:30:00,MG,381,623.2,OLIVEIRA,Falta de atenção,Colisão frontal,...,Rural,2007,9,0,4,0,5,0,4,6
2,1032898,13/08/2007,Segunda,14:25:00,MG,40,585.5,ITABIRITO,Outras,Saída de Pista,...,Rural,2007,3,0,0,1,2,0,1,1
3,1051130,12/02/2007,Segunda,02:10:00,MA,135,11.0,SAO LUIS,Animais na Pista,Atropelamento de animal,...,Urbano,2007,5,2,2,1,0,0,3,1
4,1066824,20/11/2007,Terça,05:30:00,CE,222,30.8,CAUCAIA,Defeito mecânico em veículo,Capotamento,...,Rural,2007,1,0,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158641,992957,01/08/2009,Sábado,20:30:00,BA,242,770.0,BARREIRAS,Outras,Atropelamento de pessoa,...,Rural,2009,2,0,0,1,0,1,1,1
158642,995918,15/01/2009,Quinta,09:45:00,MT,364,292.0,JACIARA,Falta de atenção,Colisão traseira,...,Rural,2009,3,0,0,0,3,0,0,3
158643,999120,30/06/2009,Terça,22:00:00,RJ,40,73.0,PETROPOLIS,Outras,Capotamento,...,Urbano,2009,1,0,0,0,1,0,0,1
158644,999150,14/07/2009,Terça,08:15:00,GO,414,281.0,VILA PROPICIO,Outras,Colisão Transversal,...,Rural,2009,3,0,0,2,1,0,2,2
158645,999845,16/06/2009,Terça,02:00:00,RJ,101,154.0,MACAE,Ultrapassagem indevida,Colisão frontal,...,Rural,2009,3,3,0,0,0,0,0,2

exportando nova versão csv

In [17]:
df_concat.to_csv('datatran_1.0.csv', 
                sep=';', 
                index=False, 
                encoding='latin1')

Removendo acentuação

In [29]:
def remove_non_ascii(string: str) -> str :
    normalized = unicodedata.normalize('NFD', string)
    return normalized.encode('ascii', 'ignore').decode('latin1')

df_concat['dia_semana'] = df_concat['dia_semana'].apply(remove_non_ascii)
df_concat['municipio'] = df_concat['municipio'].apply(remove_non_ascii)
df_concat['causa_acidente'] = df_concat['causa_acidente'].apply(remove_non_ascii)
df_concat['tipo_acidente'] = df_concat['tipo_acidente'].apply(remove_non_ascii)
df_concat['classificacao_acidente'] = df_concat['tipo_acidente'].apply(remove_non_ascii)
df_concat

,id,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,tipo_acidente,...,uso_solo,ano,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos
0,10,11/06/2007,Segunda,15:30:00,MG,381,623.2,OLIVEIRA,Falta de atencao,Colisao frontal,...,Rural,2007,9,0,4,0,5,0,4,6
1,10,11/06/2007,Segunda,15:30:00,MG,381,623.2,OLIVEIRA,Falta de atencao,Colisao frontal,...,Rural,2007,9,0,4,0,5,0,4,6
2,1032898,13/08/2007,Segunda,14:25:00,MG,40,585.5,ITABIRITO,Outras,Saida de Pista,...,Rural,2007,3,0,0,1,2,0,1,1
3,1051130,12/02/2007,Segunda,02:10:00,MA,135,11.0,SAO LUIS,Animais na Pista,Atropelamento de animal,...,Urbano,2007,5,2,2,1,0,0,3,1
4,1066824,20/11/2007,Terca,05:30:00,CE,222,30.8,CAUCAIA,Defeito mecanico em veiculo,Capotamento,...,Rural,2007,1,0,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158641,992957,01/08/2009,Sabado,20:30:00,BA,242,770.0,BARREIRAS,Outras,Atropelamento de pessoa,...,Rural,2009,2,0,0,1,0,1,1,1
158642,995918,15/01/2009,Quinta,09:45:00,MT,364,292.0,JACIARA,Falta de atencao,Colisao traseira,...,Rural,2009,3,0,0,0,3,0,0,3
158643,999120,30/06/2009,Terca,22:00:00,RJ,40,73.0,PETROPOLIS,Outras,Capotamento,...,Urbano,2009,1,0,0,0,1,0,0,1
158644,999150,14/07/2009,Terca,08:15:00,GO,414,281.0,VILA PROPICIO,Outras,Colisao Transversal,...,Rural,2009,3,0,0,2,1,0,2,2
158645,999845,16/06/2009,Terca,02:00:00,RJ,101,154.0,MACAE,Ultrapassagem indevida,Colisao frontal,...,Rural,2009,3,3,0,0,0,0,0,2

Exportando nova versão sem acentuação

In [30]:
df_concat.to_csv('datatran_1.1.csv', 
                sep=';', 
                index=False, 
                encoding='latin1')